#!/usr/bin/env bash
FORCE=0
PUSH=0
# echo "$@" # for debug
for arg
do
    case "$arg" in
        --force)
            FORCE=1
            ;;
        --push)
            PUSH=1
            ;;
    esac
done

IMAGE="dralec/${PWD##*/}"
echo "Building image: ${IMAGE}"
if [[ ${FORCE} == 0 ]]
then
  docker build -t "${IMAGE}" .
else
  docker build --no-cache -t "${IMAGE}" .
fi

if [ $? -eq 0 ]
then
  notify-send "🐳 Docker" "Built '${IMAGE}' successfully."
  if [[ ${PUSH} == 1 ]]
  then
    echo "Pushing"
    docker push "${IMAGE}"
    if [ $? -eq  0 ]; then
      notify-send "🐳 Docker" "Pushed '${IMAGE}' successfully."
    fi
  fi
else
  echo "Could not build an image" >&2
  notify-send "🐳 Docker" "'${IMAGE}' build ERROR" -u critical
  exit 1
fi
