#!/usr/bin/env bash
FORCE=0
echo "$@" # for debug
for arg
do
    case "$arg" in
        --force)
            FORCE=1
            ;;
    esac
done

IMAGE="dralec/${PWD##*/}"
echo "Building image: ${IMAGE}"
if [[ ${FORCE} == 0 ]]
then
  docker build -t "${IMAGE}" .
else
  docker build --no-cache -t "${IMAGE}" .
fi

if [ $? -eq 0 ]
then
  echo "Pushing"
  docker push "${IMAGE}"
else
  echo "Could not build an image" >&2
  exit 1
fi
